POST {{SERVER_URL}}/auth/signin
Content-Type: application/json

{
    "email": "jorgeluisrojasb@gmail.com",
    "password": "123456"
}

POST {{SERVER_URL}}/auth/signup
Content-Type: application/json

{
    "name": "Jorge Luis Rojas",
    "email": "jorgeluisrojasb@gmail.com",
    "password": "123456"
}
